### PR TITLE
Added logos for third party bundles

### PR DESCRIPTION
**Pull request by Nyholm**
Related to https://github.com/php-http/documentation/issues/123

screen shot 2016-08-22 at 15 33 11

### CODE REVIEW

**Comment by dbu** [comment]
:+1: 

@sagikazarmark any objections?

**Comment by sagikazarmark** [comment]
Looks good to me. I had the idea to have some kind of carousel, but this is perfect as well. Do we need to ask these projects if we can use their logo?

Thanks @Nyholm

**Comment by sagikazarmark** [comment]
AFAIK Payum has a logo too.

**Comment by dbu** [comment]
carousel: i'd say lets do that when we have more users
asking: if they are not happy, we can remove it. good enough?

**Comment by sagikazarmark** [comment]
Merging this for now. @Nyholm Can you add Payum logo?

**Comment by Nyholm** [comment]
Thank you for merging. 
Yes, Payum have a logo. I'll make a new PR.

**Pull request merged**
